# Generated by Django 4.2.7 on 2023-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_customer_useruid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='userUID',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
