# Generated by Django 4.2.7 on 2023-12-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_rename_path_image_image_url_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(max_length=255, upload_to=None),
        ),
    ]
