# Generated by Django 4.2.7 on 2023-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_remove_customer_useruid_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userUID',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
